### ISSUE TITLE
There is no way to copy the raw plist data to the clipboard.

### ISSUE THREAD

**Issue by chockenberry** [chockenberry/Provisioning#1]
I'd like to have way to copy the raw plist data in the .mobileprovision file to the clipboard. Unfortunately, I can't find a way to do this with the HTML presented in com.apple.quicklook.satellite process (the thing that the Quick Look daemon uses to display the HTML for the preview.)

Things I've tried:
- Displaying a dialog with the plist data using window.prompt('Here's the plist:", "xml data here"); --  WebKit has a native implementation of the prompt function on the window object, but never calls it.
- Capturing the 'copy' event and using the clipboardData object as described at https://developer.apple.com/library/mac/documentation/AppleApplications/Conceptual/SafariJSProgTopics/Tasks/CopyAndPaste.html -- text in the Quick Look web view can't be selected, so there's no way to copy it and generate the event in the first place.
- Presenting the data in a textarea element -- the information can be displayed, but not selected and copied to the clipboard.

The only thing I can think of is copying the data to NSPasteboard at the time the preview is generated. Since there would be no user action prior to this happening, using the plug-in would effectively destroy any current clipboard contents. Not good.

If anyone has any other suggestions, I'd love to hear them.

**Comment by jxpx777** [comment]
Maybe I’m not understanding 100% but I think text selection in Quick Look is [off by default](http://www.macworld.com/article/1164668/select_and_copy_text_within_quick_look_previews.html).

**Comment by command-tab** [comment]
Just spitballing here: Could the process that generates the HTML also inject JavaScript that, when executed within the HTML, trigger an event back in the parent to copy the plist data to NSPasteboard? I don't know offhand if you can trigger native calls from JavaScript like that, but perhaps.

**Comment by jxpx777** [comment]
Definitely possible to wire up a Javascript object in the code runner to point back into the Obj-C code. 1Password's new import scripts are written in Javascript and wired to Cocoa like this.

**Comment by jxpx777** [comment]
The JavascriptCore Headstart doc has info about wiring some of this stuff up. Not sure if click event handlers are propagated by default, but if so, you could create a link or button element, wire up its click event to a function that calls some hook back into the Obj-C class that set the whole thing in motion.

**Comment by atirip** [comment]
You said twice - in Quick Look web view and textarea - that text can't be selected. Please be more specific.

**Comment by chockenberry** [comment]
@atirip As @jxpx777 said, the default setting in the Quick Look web view is to disallow text selection: http://www.macworld.com/article/1164668/select_and_copy_text_within_quick_look_previews.html

**Comment by chockenberry** [comment]
@commandtab By the time the HTML is rendered in the web view, there's no link back to the Cocoa code that could do anything with NSPasteboard.

**Comment by chockenberry** [comment]
@jxpx777 Yes, events in JavaScript can be propagated back to Objective-C code. But in this case, the code that generates the HTML is long gone (the webview is actually displayed in a separate com.apple.quicklook.satellite process. ) The Cocoa code that generates the preview is run from the quicklookd process.

Also, thanks for the link about text selection being off by default. Unfortunately, since this code is running in the sandbox, I can't read that setting and change the layout dynamically (see issue #2 for details.)

**Comment by atirip** [comment]
What I meant was that one can always select text/DOM with Javascript.

**Comment by chockenberry** [comment]
@atirip Sure, you can select the text. But then what?

You can't right click on it and select "Copy". And there doesn't appear to be a way to modify the clipboard once the text is selected (the clipboardData object can only be queried after the copy event caused by user interaction.)

**Comment by atirip** [comment]
I have no idea on how it is done there. On a webpage this means somebody has canceled mouse events on right click. Maybe the selection preventing is also done that way -  the best is to cancel mousedown. One can try to add mousedown listener to document (topmost element) with capture set to true and then call stopPropagation in hope that those cancelling handlers get never called. But this would be a hack, not solid solution.

**Comment by chockenberry** [comment]
I'm going to close this issue. I added a link to the article that @jxpx777 provided in both the preview and the setup instructions.
