### ISSUE TITLE
Feature Request: display provisioning profile type (development, ad-hoc, appstore, enterprise)

### ISSUE THREAD

**Issue by pieterclaerhout** [chockenberry/Provisioning#3]
It would be really useful to mention the provisioning profile type in the info.

If you need info on how to determine these, I can probably submit a pull request.

Regards,

pieter

**Comment by chockenberry** [comment]
I'd like to that info, too. The only way I know to differentiate between them is if it has devices or not (ad-hoc vs. distribution.) Also, I've never seen a .mobileprovision for enterprise, so I have nothing to test against.

I'd love to see a pull request with what you're thinking…

**Comment by pieterclaerhout** [comment]
Done.

I've also added support for mac app provisioning profiles.

**Comment by chockenberry** [comment]
Closing this issue: will be in 1.0.2 release.
